{
 "title": "Termostato",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stations",
    "label": "Estaciones",
    "query": "select station_id from startup where date > now() - interval '1 week' and station_id is not null order by station_id desc"
   }
  ]
 },
 "panels": [
  { "title": "Controles", "type": "volkovlabs-form-panel", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resumen global",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date,\n  setted as Establecida\nFROM\n  setted \nWHERE\n  date = (select max(date) from setted)"
    },
    {
     "rawSql": "SELECT\n  date,\n  status as \"estado actual\"\nFROM\n  status\nWHERE\n  date = (select max(date) from status)"
    },
    {
     "rawSql": "SELECT\n  date,\n  case\n    when mode = 'L' then 1\n    else 0\n  end as \"modo actual\"\nFROM\n  mode\nWHERE\n  date = (\n    select\n      max(date)\n    from\n      mode\n  )"
    },
    {
     "rawSql": "SELECT count(*) as \"horas encendido\"\nfrom status \nWHERE status = 1\nand $__timeFilter(date) "
    }
   ]
  },
  { "title": "Estacion $stations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "stations" },
  {
   "title": "Actual",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  temperature as Temperatura\nFROM\n  read\nWHERE\n  date = (select max(date) from read where station_id = $stations)\n  and station_id = $stations"
    },
    {
     "rawSql": "SELECT\n  $__time(date),\n  humidity as Humedad\nFROM\n  read\nWHERE\n  date = (select max(date) from read where station_id = $stations)\n  and station_id = $stations"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  temperature as \"Temperatura\"\nFROM\n  read\nWHERE\n  $__timeFilter(date)\n  and station_id = $stations"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  humidity as \"Humedad\"\nFROM\n  read\nWHERE\n  $__timeFilter(date)\n  and station_id = $stations"
    }
   ]
  },
  {
   "title": "Último arranque",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  extract(epoch from (max(date))) * 1000 uptime\nFROM\n  startup \nwhere\n  station_id = $stations"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Estado",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  date,\n  status\nFROM\n  status \nWHERE\n  $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "Modo",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  date,\n  case\n    when mode = 'L' then 1\n    else 0\n  end as \"modo actual\"\nFROM\n  mode\nWHERE\n  $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "Últimas actualizaciones",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "select * from (\nSELECT MAX(date) as Fecha, 'Lectura' as Última, station_id FROM read where station_id is not null group by station_id\nunion\nSELECT MAX(date) as Fecha, 'Actualización de estado' as Última, 'N/A' FROM status\nunion\nSELECT MAX(date) as Fecha, 'Actualización de modo' as Última, 'N/A' FROM mode\nunion\nSELECT MAX(date) as Fecha, 'Establecimiento de temperatura' as Última, 'N/A' FROM setted \nunion\nSELECT MAX(date) as Fecha, 'Arranqe' as Última, station_id FROM startup where station_id is not null group by station_id\n) sq order by fecha DESC"
    }
   ]
  }
 ]
}